In [1]:
from sklearn.tree import DecisionTreeClassifier

In [2]:
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()
X,y = data.data, data.target

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X_test, X_train, y_test, y_train = train_test_split(X,y, test_size=0.33)

In [5]:
from sklearn.pipeline import Pipeline,make_pipeline

In [6]:
from sklearn.model_selection import GridSearchCV

In [15]:
param_grid = {"max_depth":[3,5,7,10],
             "min_samples_leaf":[5,10,15]}

gs = GridSearchCV(DecisionTreeClassifier(),param_grid, cv = 5)

In [22]:
gs.fit(X_train,y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'max_depth': [3, 5, 7, 10], 'min_samples_leaf': [5, 10, 15]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [17]:
gs.best_params_

{'max_depth': 3, 'min_samples_leaf': 5}

In [18]:
from sklearn.metrics import accuracy_score

In [19]:
accuracy_score(gs.best_estimator_.predict(X_test),y_test)

0.9448818897637795

In [20]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [28]:
import sklearn
sklearn.tree.export_graphviz(model, out_file="tree.dot")

## zbior1.txt

In [24]:
import numpy as np 

In [25]:
dane = np.loadtxt('./zbior1.txt')

In [26]:
X = dane[:,:2]
y = dane[:,2]

In [35]:
X_test, X_train, y_test, y_train = train_test_split(X,y, test_size=100)

## DecisionTreeClasifier

In [34]:
param_grid = {"max_depth":[3,5,7,10],
             "min_samples_leaf":[5,10,15]}

gs = GridSearchCV(DecisionTreeClassifier(),param_grid, cv = 5)
gs.fit(X_train,y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'max_depth': [3, 5, 7, 10], 'min_samples_leaf': [5, 10, 15]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [30]:
gs.best_params_

{'max_depth': 5, 'min_samples_leaf': 5}

In [31]:
accuracy_score(gs.best_estimator_.predict(X_test),y_test)

0.9047619047619048

## LogisticRegression

In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [41]:
pipe = Pipeline([("standarization",StandardScaler()),
                ("logreg",LogisticRegression())])

In [42]:
pipe.fit(X_train,y_train)

Pipeline(memory=None,
     steps=[('standarization', StandardScaler(copy=True, with_mean=True, with_std=True)), ('logreg', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))])

In [43]:
param_grid = {"penalty":["l1", "l2"],
             "C":[10,1,0.1,0.01]}

gs = GridSearchCV(LogisticRegression(),param_grid, cv = 5)

In [47]:
gs.fit(X_train,y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'penalty': ['l1', 'l2'], 'C': [10, 1, 0.1, 0.01]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [48]:
gs.best_params_

{'C': 10, 'penalty': 'l1'}

In [49]:
accuracy_score(gs.best_estimator_.predict(X_test),y_test)

0.475

In [50]:
from sklearn.datasets import load_iris

In [52]:
iris = load_iris()
X, y = iris.data, iris.target

In [60]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [61]:
np.unique(y)

array([0, 1, 2])

In [94]:
X_test, X_train, y_test, y_train = train_test_split(X,y, test_size=0.5)

In [95]:
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [96]:
model.predict(X_test)

array([2, 2, 2, 0, 0, 2, 1, 1, 2, 0, 1, 1, 0, 2, 2, 2, 2, 2, 2, 1, 2, 0,
       0, 1, 1, 2, 2, 1, 2, 2, 2, 2, 1, 0, 1, 1, 2, 1, 2, 0, 0, 2, 0, 0,
       2, 1, 1, 2, 0, 1, 0, 2, 1, 1, 1, 0, 1, 2, 0, 2, 2, 0, 2, 0, 1, 2,
       1, 1, 2, 2, 0, 1, 2, 1, 1])

In [97]:
model.predict_proba(X_test)

array([[1.42909466e-04, 4.47975241e-01, 5.51881849e-01],
       [1.02571724e-03, 2.50126591e-01, 7.48847692e-01],
       [4.79558381e-03, 4.90210316e-01, 5.04994100e-01],
       [8.59318824e-01, 1.39923336e-01, 7.57840039e-04],
       [9.46521825e-01, 5.33876870e-02, 9.04876094e-05],
       [3.53373714e-03, 3.70340735e-01, 6.26125528e-01],
       [5.44020818e-02, 6.22121613e-01, 3.23476305e-01],
       [1.43309525e-01, 6.44419903e-01, 2.12270572e-01],
       [2.10405072e-03, 3.95319292e-01, 6.02576657e-01],
       [8.35537326e-01, 1.64004929e-01, 4.57745088e-04],
       [9.25756911e-03, 5.21325900e-01, 4.69416531e-01],
       [1.24683467e-01, 6.72857547e-01, 2.02458986e-01],
       [9.18290360e-01, 8.10143545e-02, 6.95285985e-04],
       [5.02383963e-04, 4.43190076e-01, 5.56307540e-01],
       [2.85721543e-03, 3.29946076e-01, 6.67196709e-01],
       [8.54017946e-04, 3.56474117e-01, 6.42671865e-01],
       [1.37461182e-03, 3.13815674e-01, 6.84809714e-01],
       [2.39740479e-03, 3.72935

In [98]:
accuracy_score(y_test, model.predict(X_test))

0.9733333333333334

In [99]:
model.coef_

array([[ 0.36991667,  1.29160107, -1.97545897, -0.91334444],
       [ 0.35381003, -1.41382187,  0.51087824, -0.78443135],
       [-1.19877294, -1.29184959,  1.88853996,  1.65067421]])

In [100]:
from sklearn.metrics import confusion_matrix

In [101]:
confusion_matrix(y_test,model.predict(X_test))

array([[18,  0,  0],
       [ 0, 25,  2],
       [ 0,  0, 30]])

In [102]:
model = DecisionTreeClassifier(min_samples_leaf=5)
model.fit(X_train,y_train)
accuracy_score(y_test, model.predict(X_test))

0.9333333333333333

In [103]:
confusion_matrix(y_test,model.predict(X_test))

array([[18,  0,  0],
       [ 0, 23,  4],
       [ 0,  1, 29]])

In [104]:
model.predict_proba(X_test)

array([[0.        , 0.        , 1.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 0.        , 1.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 0.66666667, 0.33333333],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 1.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [1.        , 0.        , 0.        ],
       [1.